server.port: 9090
spring:
  kafka.bootstrap-servers: localhost:9092
  kafka.consumer.bootstrap-servers: localhost:9092
  cloud.stream.kafka.streams.binder.brokers: localhost:9092
  cloud.stream.kafka.binder.brokers: localhost:9092
  cloud.stream.kafka.binder.zkNodes: localhost:2181
  cloud.stream.kafka.streams:
    binder:
      application-id: demo-application
      min-partition-count: 1
      auto-add-partitions: false
      configuration:
        num.stream.threads: 1
        key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default:
          key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  cloud.stream.bindings:
    topicA-in:
      group: topicAInGroup
      destination: topicA
      consumer:
        instance-count: 2
        instance-index: 1
        headerMode: headers
        concurrency: 10
        partitioned: true
      producer:
        headerMode: headers
    topicB-in:
      group: topicBInGroup
      destination: topicB
      consumer:
        instance-count: 2
        instance-index: 1
        headerMode: headers
        concurrency: 1
        partitioned: false
      producer:
        headerMode: headers
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
